name: deploy gym-web

on:
  push:
    branches:
      - "main" # 针对 main 分支
    paths:
      - ".github/workflows/*"
      - "src/**"
      - "public/*"
      - "package.json"
      - "vite.config.ts"
      - "index.html"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v3

      - name: 设置 node 环境
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.2"

      - name: 安装依赖
        run: npm install

      - name: 编译打包
        run: npm run build

      - name: Copy Files 2 Server
        uses: appleboy/scp-action@master
        with:
            host: ${{secrets.REMOTE_HOST}}
            username: "root"
            password: "Lw951207"
            port: 22
            source: "dist"
            target: "/root/gym/web"

