name: deploy gym-web

on:
  push:
    branches:
      - "main" # 针对 main 分支
    paths:
      - ".github/workflows/*"
      - "src/**"
      - "public/*"
      - "package.json"
      - "vite.config.ts"
      - "index.html"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v3

      - name: 设置 node 环境
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.2"

      - name: 安装依赖
        run: npm install

      - name: 编译打包
        run: npm run build

      - name: 设置 id_rsa
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.GYM}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 120.26.128.30 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: 将远程服务器的对应目录下所有文件及文件夹删除
        run: | # gym/web
          ssh root@120.26.128.30 "
            cd /root/${{secrets.REMOTE_WEB_DIR}};
            rm -rf ./*;
          "

      - name: 将编译后的包复制到远程服务器对应目录
        run: scp -r ./dist root@${{secrets.REMOTE_HOST}}:/root/${{secrets.REMOTE_WEB_DIR}}

      - name: 删除 id_rsa
        run: rm -rf ~/.ssh/id_rsa
